import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { runInNewContext } from 'node:vm'
import test from 'node:test'
import ts from 'typescript'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const read = (path) => readFileSync(resolve(root, path), 'utf8')

function loadPersonalityHelpers() {
  const source = read('src/lib/compatibilityPersonality.ts')
  const output = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2020,
    },
  }).outputText
  const exports = {}
  runInNewContext(output, { exports })
  return exports
}

test('compatibility personality helper exposes the retained APIs', () => {
  const source = read('src/lib/compatibilityPersonality.ts')

  assert.match(source, /export function buildPersonalityValidationPlan/)
  assert.match(source, /export function getPersonalityMatchType/)
  assert.match(source, /export function getCompatibilityQuestionLabel/)
  assert.match(source, /export function buildPersonalityConsultationPreview/)
  // deterministic portrait engine removed (personality now generated by the AI report)
  assert.doesNotMatch(source, /export function buildPersonalityFitSummary/)
})

test('personality validation plan uses conditional 7-day and 30-day observation language', () => {
  const { buildPersonalityValidationPlan } = loadPersonalityHelpers()
  const plan = buildPersonalityValidationPlan({
    questionLabel: '值不值得继续投入',
    matchType: '慢热磨合型',
    advice: {
      recommendation: 'observe',
      confidence: 'medium',
      conditions: ['确认对方是否能稳定回应'],
      do_next: ['先观察互动节奏'],
      avoid: ['不要过早加码投入'],
    },
    stageRisks: [
      {
        window: 'three_months',
        risk_level: 'medium',
        main_risk: '沟通节奏不一致',
        trigger: '推进关系时',
        advice: '先观察修复能力。',
        evidence_keys: ['comm-risk'],
      },
    ],
    hasEvidence: true,
  })

  assert.match(plan.shortTerm.title, /7 天/)
  assert.match(plan.mediumTerm.title, /30 天/)
  assert.match(plan.shortTerm.items.join(' '), /观察|确认|验证/)
  assert.match(plan.mediumTerm.items.join(' '), /观察|确认|验证/)
  assert.match(plan.avoid.items.join(' '), /不要|避免|暂缓/)
  assert.doesNotMatch(JSON.stringify(plan), /一定|必然|结婚日期|分手日期/)
})

test('compatibility entry puts personality consultation before birth profile forms', () => {
  const page = read('src/pages/CompatibilityPage.tsx')
  const css = read('src/pages/CompatibilityPage.css')

  const intro = page.indexOf('compatibility-personality-consultation')
  const preview = page.indexOf('compatibility-personality-preview')
  const forms = page.indexOf('compatibility-forms')
  const payload = page.indexOf('relationship_stage: relationshipStage')

  assert.ok(intro > -1, 'personality consultation section exists')
  assert.ok(preview > intro, 'preview follows consultation controls')
  assert.ok(forms > preview, 'birth forms follow personality preview')
  assert.ok(payload > -1, 'existing payload keeps relationship context')
  assert.match(page, /性格合不合/)
  assert.match(css, /compatibility-personality-consultation/)
  assert.match(css, /compatibility-personality-preview/)
})

test('compatibility result keeps narrative order and renders personality in the AI report', () => {
  const page = read('src/pages/CompatibilityResultPage.tsx')
  const sectionDeep = read('src/components/compatibility/SectionDeepAnalysis.tsx')
  const deepReport = read('src/components/compatibility/deep-analysis/DeepReportNarrative.tsx')

  // narrative layout: Verdict (分数) → SectionDeepAnalysis → EvidenceDrawer → AI 深度解读 (last)
  const verdict = page.indexOf('<SectionVerdict')
  const deep = page.indexOf('<SectionDeepAnalysis')
  const drawer = page.indexOf('<EvidenceDrawer')
  const report = page.indexOf('<DeepReportNarrative')
  assert.ok(verdict > -1, 'SectionVerdict renders scores')
  assert.ok(deep > verdict, 'SectionDeepAnalysis follows verdict (scores)')
  assert.ok(drawer > deep, 'EvidenceDrawer follows deep analysis')
  assert.ok(report > drawer, 'AI 深度解读 is the last block, after EvidenceDrawer')

  // no standalone personality SECTION on the page anymore
  assert.doesNotMatch(page, /PersonalityFit/)

  // deep analysis inner order: 关系策略 → 阶段风险 → 下一步（AI 深度解读在页面末尾）
  const strategy = sectionDeep.indexOf('<RelationshipStrategy')
  const action = sectionDeep.indexOf('<ActionPlan7d30d')
  const next = sectionDeep.indexOf('<NextStepsAndAvoid')
  assert.ok(strategy > -1 && strategy < action && action < next, 'deep analysis sub-blocks ordered 策略→风险→下一步')
  assert.doesNotMatch(sectionDeep, /DeepReportNarrative/)

  // 双方性格画像与差异 now lives in the AI report (LLM-generated)
  assert.match(deepReport, /<PersonalityComparison comparison=\{structuredReport\.personality_comparison\} \/>/)

  // 7-day / 30-day validation titles are still generated by the personality helper
  const personalityHelper = read('src/lib/compatibilityPersonality.ts')
  assert.match(personalityHelper, /7 天观察/)
  assert.match(personalityHelper, /30 天验证/)
})

test('compatibility history highlights personality match type and continuation action', () => {
  const page = read('src/pages/CompatibilityHistoryPage.tsx')
  const css = read('src/pages/CompatibilityHistoryPage.css')

  assert.match(page, /getPersonalityMatchType/)
  assert.match(page, /compatibility-history-personality/)
  assert.match(page, /性格匹配/)
  assert.match(page, /继续看性格合盘|生成深度解读|查看性格合盘/)
  assert.match(css, /compatibility-history-personality/)
  assert.match(css, /compatibility-history-continuation/)
})
