import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'
import assert from 'node:assert/strict'

const root = new URL('..', import.meta.url).pathname
function read(path) {
  return readFileSync(join(root, path), 'utf8')
}

test('ResultPage declares and renders vehicle-road fields', () => {
  const src = read('src/pages/ResultPage.tsx')
  assert.match(src, /interface VehicleProfile/)
  assert.match(src, /interface WealthProfile/)
  assert.match(src, /interface WealthWindowHint/)
  assert.match(src, /interface DayunRoad/)
  assert.match(src, /vehicle_profile\?: VehicleProfile/)
  assert.match(src, /wealth_profile\?: WealthProfile/)
  assert.match(src, /driving_style\?: string/)
  assert.match(src, /risk_flags: string\[\]/)
  assert.match(src, /current_hint\?: WealthWindowHint/)
  assert.match(src, /dayun_roadmap\?: DayunRoad\[\]/)
  assert.match(src, /natal_assessment\?: NatalAssessment/)
  assert.match(src, /命盘座驾/)
  assert.match(src, /财富结构/)
  assert.match(src, /当前路况/)
  assert.match(src, /result\.vehicle_profile &&/)
  assert.match(src, /const wealthProfile = result\.wealth_profile/)
  assert.match(src, /findDayunRoad\(result\.dayun_roadmap,\s*currentDayun\)/)
})

test('ResultPage exposes professional evidence and fallback-safe rendering', () => {
  const src = read('src/pages/ResultPage.tsx')
  assert.match(src, /const vehicleEvidences = result\.vehicle_profile\?\.evidences \?\? \[\]/)
  assert.match(src, /readingMode === 'professional'[\s\S]+?vehicleEvidences\.length > 0/)
  assert.match(src, /const currentRoadEvidences = currentDayunRoad\?\.evidences \?\? \[\]/)
  assert.match(src, /readingMode === 'professional'[\s\S]+?hasCurrentRoadEvidence/)
  assert.match(src, /currentDayun \? \(/)
  assert.match(src, /currentDayun\.start_age/)
  assert.match(src, /currentRoadPhasePrompts\.length > 0/)
  assert.match(src, /formatEvidenceDelta/)
  assert.match(src, /const vehicleDrivingStyle = result\.vehicle_profile\?\.driving_style/)
  assert.match(src, /const wealthEvidences = wealthProfile\?\.evidences \?\? \[\]/)
  assert.match(src, /readingMode === 'professional'[\s\S]+?wealthEvidences\.length > 0/)
  assert.match(src, /overviewModal === 'wealth-evidence'/)
  assert.match(src, /不参与基础盘等级或主车型判定/)
  assert.match(src, /不等于现实资产、收入规模或投资建议/)
})

test('ResultPage refreshes historical charts so saved-state snapshots receive wealth backfills', () => {
  const src = read('src/pages/ResultPage.tsx')
  assert.match(src, /历史详情始终以服务端结果为准/)
  assert.match(src, /useEffect\(\(\) => \{\s*if \(id\) \{\s*baziAPI\.getHistoryDetail\(id\)/)
  assert.doesNotMatch(src, /if \(id && !result\) \{\s*baziAPI\.getHistoryDetail\(id\)/)
})

test('ResultPage presents global Fuyi conclusions instead of the legacy Tiaohou field', () => {
  const src = read('src/pages/ResultPage.tsx')
  assert.match(src, /function getFuyiYongshen/)
  assert.match(src, /result\.natal_assessment\?\.fuyi\.yongshen \|\| result\.yongshen/)
  assert.match(src, /扶抑喜用：\{fuyiYongshen/)
  assert.match(src, /扶抑忌：\{fuyiJishen/)
  assert.match(src, /<YongshenBadge yongshen=\{fuyiYongshen\} jishen=\{fuyiJishen\}/)
})

test('ResultPage displays shared-priority yongshen without replacing Fuyi', () => {
  const src = read('src/pages/ResultPage.tsx')
  const css = read('src/pages/ResultPage.css')
  assert.match(src, /yongshen_alignment\?: \{ elements: string\[\]; source_layers: string\[\]; detail\?: string \}/)
  assert.match(src, /共同优先用神：/)
  assert.match(src, /同时属于寒热调候与扶抑；不替代完整扶抑喜用。/)
  assert.match(css, /\.result-shared-yongshen/)
})

test('ResultPage keeps day-stem and thermal Tiaohou distinct', () => {
  const src = read('src/pages/ResultPage.tsx')
  const card = read('src/components/TiaohouCard.tsx')
  assert.match(src, /tiaohou\?: \{[\s\S]+?day_stem:[\s\S]+?thermal:/)
  assert.match(src, /<ThermalTiaohouCard thermal=\{result\.natal_assessment\.tiaohou\.thermal\}/)
  assert.match(src, /score=\{result\.natal_assessment\?\.tiaohou\?\.day_stem\.score\}/)
  assert.match(src, /formation=\{result\.natal_assessment\?\.tiaohou\?\.day_stem\.formation\}/)
  assert.match(src, /foundationScore=\{result\.natal_assessment\?\.tiaohou\?\.day_stem\.foundation_score\}/)
  assert.match(src, /日干调候与寒热调候分别呈现/)
  assert.match(card, /日干调候/)
  assert.match(card, /日干调候成格 · 高格基础/)
  assert.match(card, /\+\{score\} 分/)
})

test('ResultPage explains grade and road labels in ordinary-user language', () => {
  const src = read('src/pages/ResultPage.tsx')
  assert.match(src, /const VEHICLE_GRADE_GUIDE = \[/)
  assert.match(src, /上格配置/)
  assert.match(src, /中上格配置/)
  assert.match(src, /中格配置/)
  assert.match(src, /中下格配置/)
  assert.match(src, /下格配置/)
  assert.match(src, /超跑级座驾/)
  assert.match(src, /高性能车级座驾/)
  assert.match(src, /标准轿车级座驾/)
  assert.match(src, /实用 MPV 级座驾/)
  assert.match(src, /基础代步单车级/)
  assert.match(src, /调候急需优先；无急需时以扶抑为基线，再看日干调候成格、主格结构、制化与流通/)
  assert.match(src, /const ROAD_GUIDE = \[/)
  assert.match(src, /大运路况说明/)
  assert.match(src, /车代表命盘的基础配置与驾驭难度/)
  assert.match(src, /currentRoadGuide\.summary/)
  assert.match(src, /VEHICLE_GRADE_TAGS/)
  assert.match(src, /LEGACY_VEHICLE_TYPE_TAGS/)
  assert.match(src, /vehicleGradeGuide\?\.vehicle \|\| result\.vehicle_profile\?\.vehicle_type/)
})

test('ResultPage separates high day-stem foundation from primary-pattern structure', () => {
  const src = read('src/pages/ResultPage.tsx')
  assert.match(src, /foundation_source\?: string/)
  assert.match(src, /foundation_tier === 'high'/)
  assert.match(src, /日干调候成格.*高格基础/)
  assert.match(src, /主格结构：/)
  assert.match(src, /制化配合：/)
})

test('ResultPage keeps overview actions with their summary cards instead of disclosure blocks', () => {
  const src = read('src/pages/ResultPage.tsx')
  const verdict = src.indexOf('className="result-verdict-card result-conclusion-panel"')
  const overview = src.indexOf('className={`result-summary-grid')
  const vehicle = src.indexOf('className="result-vehicle-card result-summary-card')
  const wealth = src.indexOf('className="result-wealth-card result-summary-card')
  const currentRoad = src.indexOf('className="result-current-card result-summary-card')

  assert.ok(verdict > -1 && overview > verdict, 'the verdict should precede the summary grid')
  assert.ok(vehicle > overview && wealth > vehicle && currentRoad > wealth, 'vehicle, wealth, and current road should render in DOM order')
  assert.doesNotMatch(src, /result-overview-support/)
  assert.doesNotMatch(src, /result-overview-disclosure/)
  assert.match(src, /className="result-overview-actions"/)
  assert.match(src, /openOverviewModal\('grade', event\.currentTarget\)/)
  assert.match(src, /openOverviewModal\('road', event\.currentTarget\)/)
  assert.match(src, /openOverviewModal\('vehicle-evidence', event\.currentTarget\)/)
  assert.match(src, /openOverviewModal\('wealth-evidence', event\.currentTarget\)/)
  assert.match(src, /openOverviewModal\('road-evidence', event\.currentTarget\)/)
  assert.match(src, /\n\s*等级说明\n\s*<\/button>/)
  assert.match(src, /S 到 D 区分原局基础层次/)
  assert.match(src, /VEHICLE_GRADE_GUIDE\.map/)
  assert.match(src, /item\.grade === result\.vehicle_profile\?\.grade \? 'is-current'/)
  assert.match(src, /\n\s*查看路况与阶段提示说明\n\s*<\/button>/)
  assert.match(src, /查看座驾依据/)
  assert.match(src, /查看财富依据/)
  assert.match(src, /查看路况依据/)
})

test('ResultPage uses one accessible modal for overview guidance and evidence', () => {
  const src = read('src/pages/ResultPage.tsx')
  assert.match(src, /type OverviewModalKind = 'grade' \| 'road' \| 'vehicle-evidence' \| 'road-evidence' \| 'wealth-evidence'/)
  assert.match(src, /const \[overviewModal, setOverviewModal\] = useState<OverviewModalKind \| null>\(null\)/)
  assert.match(src, /role="dialog"/)
  assert.match(src, /aria-modal="true"/)
  assert.match(src, /onMouseDown=\{event => \{[\s\S]+?event\.target === event\.currentTarget/)
  assert.match(src, /event\.key === 'Escape'/)
  assert.match(src, /document\.body\.style\.overflow = 'hidden'/)
  assert.match(src, /overviewModalTriggerRef\.current\?\.focus\(\)/)
  assert.match(src, /overviewModal === 'grade'/)
  assert.match(src, /overviewModal === 'road'/)
  assert.match(src, /overviewModal === 'wealth-evidence'/)
  assert.match(src, /item\.type === currentDayunRoad\?\.road_type \? 'is-current'/)
})

test('DayunTimeline receives roadmap and renders road labels and phases', () => {
  const src = read('src/components/DayunTimeline.tsx')
  assert.match(src, /dayunRoadmap\?: DayunRoad\[\]/)
  assert.match(src, /roadByDayunIndex/)
  assert.match(src, /dayun-road-badge/)
  assert.match(src, /十年综合路况/)
  assert.match(src, /前后五年阶段指引/)
  assert.match(src, /主题：\{prompt\.theme\}/)
  assert.match(src, /getDayunPhasePrompt/)
})

test('Result CSS includes compact vehicle and road treatments', () => {
  const css = read('src/pages/ResultPage.css')
  assert.match(css, /\.result-vehicle-card/)
  assert.match(css, /\.result-vehicle-meter/)
  assert.match(css, /\.result-road-phase-prompts/)
  assert.match(css, /\.result-profile-evidence/)
  assert.match(css, /\.result-profile-driving-style/)
  assert.match(css, /\.result-overview-actions/)
  assert.match(css, /\.result-overview-modal\s*\{/)
  assert.match(css, /\.result-overview-modal__dialog/)
  assert.match(css, /\.result-overview-modal__body/)
  assert.match(css, /\.result-grade-guide/)
  assert.match(css, /\.result-grade-guide li\.is-current/)
  assert.match(css, /\.result-road-guide li\.is-current/)
  assert.match(css, /\.result-road-guide/)
  assert.match(css, /\.result-profile-plain-note/)
  assert.match(css, /\.result-summary-card--wealth/)
  assert.match(css, /\.result-wealth-meter/)
  assert.match(css, /\.result-wealth-current-hint/)
  assert.match(css, /\.result-wealth-risk-list/)
  assert.match(css, /\.dayun-road-badge/)
  assert.match(css, /\.dayun-road-summary/)
  assert.match(css, /\.result-summary-grid\s*\{[\s\S]*align-items:\s*start;/)
  assert.match(css, /\.result-summary-card--vehicle/)
  assert.match(css, /\.result-current-year\s*\{[\s\S]*border-top:/)
  const verdictRules = css.match(/\.result-verdict-card\s*\{([^}]*)\}/)?.[1] || ''
  assert.doesNotMatch(verdictRules, /\border\s*:/)
})

test('ResultPage keeps the conclusion chain ahead of utility and reference reading', () => {
  const src = read('src/pages/ResultPage.tsx')
  const identity = src.indexOf('className="result-identity-panel animate-fade-up"')
  const verdict = src.indexOf('className="result-verdict-card result-conclusion-panel"')
  const summary = src.indexOf('className={`result-summary-grid')
  const utility = src.indexOf('chart-archive-tools result-utility-bar')
  const trend = src.indexOf('id="result-section-trend"')
  const historicalReference = src.lastIndexOf('{historicalFiguresSection}')

  assert.ok(verdict > -1 && summary > verdict, 'summary should follow the core conclusion')
  assert.ok(identity > -1 && utility > identity && utility < verdict, 'management tools should belong to the identity region')
  assert.ok(trend > summary, 'trend reading should follow the concise summary')
  assert.ok(historicalReference > trend, 'historical reference should be progressive reading')
  assert.match(src, /const historicalFiguresSection = result\.ming_ge && historicalFigures\.length > 0/)
  assert.match(src, /result\.vehicle_profile \? '' : ' is-single-panel'/)
})

test('ResultPage uses separate identity, conclusion, vehicle, and road boundaries', () => {
  const src = read('src/pages/ResultPage.tsx')
  const css = read('src/pages/ResultPage.css')

  const identity = src.indexOf('className="result-identity-panel animate-fade-up"')
  const conclusion = src.indexOf('className="result-verdict-card result-conclusion-panel"')
  const summary = src.indexOf('className="result-summary-region" aria-label="本命与当下"')
  const vehicle = src.indexOf('className="result-vehicle-card result-summary-card')
  const wealth = src.indexOf('className="result-wealth-card result-summary-card')
  const road = src.indexOf('className="result-current-card result-summary-card')

  assert.ok(identity > -1 && conclusion > identity && summary > conclusion, 'primary regions should follow identity, conclusion, summary order')
  assert.ok(vehicle > summary && wealth > vehicle && road > wealth, 'vehicle should precede wealth and road within the summary region')
  assert.match(src, /className="result-identity-side"/)
  assert.match(src, /className="result-identity-side-label">阅读视图/)
  assert.match(src, /result-conclusion-panel[\s\S]+?result-quick-summary/)
  assert.match(css, /\.result-identity-panel\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\) auto;/)
  assert.match(css, /\.result-conclusion-panel\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\) minmax\(260px,\s*0\.9fr\);/)
  assert.match(css, /\.result-summary-grid\s*\{[\s\S]*gap:\s*18px;/)
  assert.match(css, /@media \(max-width: 760px\)\s*\{[\s\S]*\.result-identity-panel\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\);/)
})

test('ResultPage preserves the same summary structure in professional mode', () => {
  const src = read('src/pages/ResultPage.tsx')
  const historicalDefinition = src.indexOf('const historicalFiguresSection')
  const summary = src.indexOf('className={`result-summary-grid')

  assert.ok(summary > historicalDefinition, 'mode-specific historical details should not alter summary placement')
  assert.match(src, /readingMode === 'professional' && vehicleEvidences\.length > 0/)
  assert.match(src, /readingMode === 'professional' && wealthEvidences\.length > 0/)
  assert.match(src, /readingMode === 'professional' && hasCurrentRoadEvidence/)
})

test('ResultPage renders phase-aware road evidence with aggregate-only fallback', () => {
  const src = read('src/pages/ResultPage.tsx')
  const css = read('src/pages/ResultPage.css')

  assert.match(src, /interface DayunPhaseEvidence/)
  assert.match(src, /phase_evidences\?: DayunPhaseEvidence\[\]/)
  assert.match(src, /const currentRoadPhaseEvidences = currentDayunRoad\?\.phase_evidences \?\? \[\]/)
  assert.match(src, /const hasCurrentRoadEvidence = currentRoadEvidences\.length > 0 \|\| currentRoadPhaseEvidences\.length > 0/)
  assert.match(src, /十年合计/)
  assert.match(src, /阶段合计 \{formatEvidenceDelta\(phase\.delta\)\}/)
  assert.match(src, /currentRoadPhaseEvidences\.length > 0 \? \(/)
  assert.match(src, /\) : \(\s*<ul className="result-profile-evidence">/)
  assert.match(css, /\.result-road-evidence-phases/)
  assert.match(css, /\.result-road-evidence-phase-heading/)
})

test('ResultPage presents exact stem-level yongshen summary with a legacy element fallback', () => {
  const src = read('src/pages/ResultPage.tsx')
  const css = read('src/pages/ResultPage.css')

  assert.match(src, /interface NatalStemGuidanceItem/)
  assert.match(src, /stem_guidance\?: NatalStemGuidance/)
  assert.match(src, /interface StemLevelYongshenSummary/)
  assert.match(src, /function buildStemLevelYongshenSummary/)
  assert.match(src, /function StemLevelYongshenSummaryPanel/)
  assert.match(src, /function StemGuidanceInlineList/)
  assert.match(src, /const stemSummary = buildStemLevelYongshenSummary\(result\)/)
  assert.match(src, /function StemGuidancePanel/)
  assert.match(src, /primary_favorable/)
  assert.match(src, /secondary_favorable/)
  assert.match(src, /conditioning_only/)
  assert.match(src, /adverse/)
  assert.match(src, /首取/)
  assert.match(src, /扶抑可用/)
  assert.match(src, /扶抑慎用/)
  assert.match(src, /调候参考/)
  assert.match(src, /stemLevelYongshenSummary \? \(/)
  assert.match(src, /const resultQuickSummary = stemLevelYongshenSummary/)
  assert.match(src, /扶抑可用\$\{formatStemGuidanceItems\(stemSummary\.usable\)/)
  assert.match(src, /慎用\$\{formatStemGuidanceItems\(stemSummary\.adverse\)/)
  assert.match(src, /扶抑喜用：\{fuyiYongshen/)
  assert.match(src, /<YongshenBadge yongshen=\{fuyiYongshen\} jishen=\{fuyiJishen\} \/>/)
  assert.match(src, /不等同后天通用喜神/)
  assert.match(css, /\.stem-guidance-panel/)
  assert.match(css, /\.stem-guidance-group--primary/)
  assert.match(css, /\.stem-guidance-group--adverse/)
  assert.match(css, /\.result-stem-summary/)
  assert.match(css, /\.result-stem-summary-row--primary/)
  assert.match(css, /\.result-stem-summary-row--adverse/)
  assert.match(css, /@media \(max-width: 760px\)[\s\S]+?\.result-stem-summary-row/)
})
