import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(__dirname, '../..')
const read = (path: string) => readFileSync(resolve(root, path), 'utf8')

describe('article frontend wiring', () => {
  it('registers user article routes and top navigation entry', () => {
    const app = read('src/App.tsx')
    const nav = read('src/components/Navbar.tsx')

    expect(app).toContain('path="/articles"')
    expect(app).toContain('path="/articles/:id"')
    expect(nav).toContain('to="/articles"')
    expect(nav).toContain('articleAPI.settings')
    expect(nav).toContain('articleModuleEnabled')
    expect(nav).toContain('资讯')
  })

  it('gates article pages behind auth and tracks original-link clicks', () => {
    const listPage = read('src/pages/ArticlesPage.tsx')
    const detailPage = read('src/pages/ArticleDetailPage.tsx')
    const api = read('src/lib/api.ts')

    expect(api).toContain('/api/articles/settings')
    expect(api).toContain('isArticleModuleClosedError')
    expect(listPage).toContain('<Navigate to="/login" replace />')
    expect(detailPage).toContain('<Navigate to="/login" replace />')
    expect(listPage).toContain('资讯模块暂未开放')
    expect(detailPage).toContain('资讯模块暂未开放')
    expect(listPage).toContain('isArticleModuleClosedError')
    expect(detailPage).toContain('isArticleModuleClosedError')
    expect(detailPage).toContain('articleAPI.trackOriginalClick')
    expect(detailPage).toContain('AI 摘要与仿写拆解基于')
    expect(detailPage).toContain('正文内容')
    expect(detailPage).toContain('body_content')
  })

  it('wires admin article tabs, publish confirmation, and task retry controls', () => {
    const adminPage = read('src/pages/admin/AdminArticlesPage.tsx')
    const adminDetailPage = read('src/pages/admin/AdminArticleDetailPage.tsx')
    const adminApi = read('src/lib/adminApi.ts')

    expect(adminPage).toContain("'articles'")
    expect(adminPage).toContain("'collection'")
    expect(adminPage).toContain("'content'")
    expect(adminPage).toContain("'tasks'")
    expect(adminPage).toContain('审核队列')
    expect(adminPage).toContain('资讯模块总开关')
    expect(adminPage).toContain('停止整个模块')
    expect(adminPage).toContain('模块已停止')
    expect(adminPage).toContain('moduleEnabled')
    expect(adminPage).toContain('adminArticlesAPI.getModuleSettings')
    expect(adminPage).toContain('adminArticlesAPI.updateModuleSettings')
    expect(adminPage).toContain('采集中心')
    expect(adminPage).toContain('内容配置')
    expect(adminPage).toContain('window.confirm')
    expect(adminPage).toContain('articlePage')
    expect(adminPage).toContain('articleLimit')
    expect(adminPage).toContain('toggleCurrentPageSelected')
    expect(adminPage).toContain('确认删除选中的')
    expect(adminPage).toContain('collecting')
    expect(adminPage).toContain('采集中，请稍候')
    expect(adminPage).toContain('retryingTaskID')
    expect(adminPage).toContain('重试失败')
    expect(adminPage).toContain('重试中')
    expect(adminPage).toContain('collectionConfigSaving')
    expect(adminPage).toContain('collectionConfigFeedback')
    expect(adminPage).toContain('qualityConfigFeedback')
    expect(adminPage).toContain('自动发布')
    expect(adminPage).toContain('auto_publish_enabled')
    expect(adminPage).toContain('autoPublishSummary')
    expect(adminPage).toContain('auto_published')
    expect(adminPage).toContain('auto_publish_reason')
    expect(adminPage).toContain('质量筛选')
    expect(adminPage).toContain('QualityScoreBadge')
    expect(adminPage).toContain('collectionConfigDirty')
    expect(adminPage).toContain('collectionIntervalPresets')
    expect(adminPage).toContain('保存并生效')
    expect(adminPage).toContain('已是最新')
    expect(adminPage).toContain('还原')
    expect(adminPage).toContain('保存中')
    expect(adminPage).toContain('已保存')
    expect(adminPage).toContain('保存失败')
    expect(adminPage).toContain('查看明细')
    expect(adminPage).toContain('TaskLogList')
    expect(adminPage).toContain('adminArticlesAPI.retryTask')
    expect(adminPage).toContain('adminArticlesAPI.taskItems')
    expect(adminPage).toContain('adminArticlesAPI.updateQualityConfig')
    expect(adminPage).toContain('adminArticlesAPI.batchGenerateAI')
    expect(adminPage).toContain('adminArticlesAPI.batchAction')
    expect(adminDetailPage).toContain('粘贴正文')
    expect(adminDetailPage).toContain('审核操作')
    expect(adminDetailPage).toContain('从链接补抓')
    expect(adminDetailPage).toContain('质量评估')
    expect(adminDetailPage).toContain('adminArticlesAPI.updateBody')
    expect(adminDetailPage).toContain('adminArticlesAPI.fetchBody')
    expect(adminApi).toContain('/body')
    expect(adminApi).toContain('/fetch-body')
    expect(adminApi).toContain('/module-settings')
    expect(adminApi).toContain('/collection-tasks/${id}/items')
    expect(adminApi).toContain('/quality-config')
  })
})
